as yet unclassified
renderPackingOn: xul

		xul groupbox with: [
			xul caption label: 'packing'.
			xul hbox pack: 'start'; with: [
				xul button label: 'Here'.
				xul button label: 'the'.
				xul button label: 'packing'.
				xul button label: 'is'.
				xul button label: 'start'.].
			xul hbox pack: 'center'; with: [
				xul button label: 'Here'.
				xul button label: 'the'.
				xul button label: 'packing'.
				xul button label: 'is'.
				xul button label: 'center'.].
			xul hbox pack: 'end'; with: [
				xul button label: 'Here'.
				xul button label: 'the'.
				xul button label: 'packing'.
				xul button label: 'is'.
				xul button label: 'end'.].
			xul hbox pack: 'start'; with: [
				xul button label: 'Here'.
				xul button label: 'packing'.
				xul button label: 'yields'.
				xul button label: 'to'.
				xul button label: 'flex'; flex: 1.].
		].