as yet unclassified
getData

	^ {
		PhobosDemoData name: 'Pearl' sex: #Female color: 'Gray' desc: 'Frumpy'.
		PhobosDemoData name: 'Aramis' sex: #Male color: 'Black' desc: 'Cute'.
		PhobosDemoData name: 'Yakima' sex: #Male color: 'Holstein' desc: 'Handsome'.
		PhobosDemoData name: 'Cosmo' sex: #Female color: 'White' desc: 'Round'.
		PhobosDemoData name: 'Fergus' sex: #Male color: 'Black' desc: 'Long'.
		PhobosDemoData name: 'Clint' sex: #Male color: 'Black' desc: 'Young'.
		PhobosDemoData name: 'Tribble' sex: #Female color: 'Orange' desc: 'Frumpy'.
		PhobosDemoData name: 'Zippy' sex: #Male color: 'Orange' desc: 'Playful'.
	}