as yet unclassified
pages

	^ { 
"		'Forms' -> XULPeriodicTableForms.
"
		'Images' -> PhobosDemoImages.
		'Components' -> PhobosDemoComponents.
		'Trees, Nested' -> PhobosDemoTreesNested.
		'Trees, Simple' -> PhobosDemoTreesSimple.
		'TextBoxes' -> PhobosDemoTextBoxes.
		'Tabs' -> PhobosDemoTabs.
		'Stacks and Decks' -> PhobosDemoStacksAndDecks.
		'Splitters' -> PhobosDemoSplitters.
		'Scrolling' -> PhobosDemoScrolling.
		'Buttons' -> PhobosDemoButtons.
		'Radiobuttons' -> PhobosDemoRadiobuttons.
		'Popups' -> PhobosDemoPopups.
		'Menubars, etc.' -> PhobosDemoMenubars.
		'Lists' -> PhobosDemoLists.
		'Progressmeters' -> PhobosDemoProgressmeters.
		'Labels' -> PhobosDemoLabels.
		'Grids' -> PhobosDemoGrids.
		'Cropping' -> PhobosDemoCropping.
		'Colorpickers' -> PhobosDemoColorpickers.
		'Checkboxes' -> PhobosDemoCheckboxes. 
		'Box Layout' -> PhobosDemoBoxLayout.

"
		'Call/Answer' -> XULComponent1.
		'IFrame' -> XULPeriodicTableIFrame.
		'Editor' -> XULPeriodicTableEditor."
	}