as yet unclassified
pages

	^ { 
		'Forms' -> PhobosDemoForms.
		'Box Layout' -> PhobosDemoBoxLayout.
		'Buttons' -> PhobosDemoButtons.
		'Checkboxes' -> PhobosDemoCheckboxes. 
		'Radiobuttons' -> PhobosDemoRadiobuttons.
		'Lists' -> PhobosDemoLists.
		'Images' -> PhobosDemoImages.
		'TextBoxes' -> PhobosDemoTextBoxes.
		'Colorpickers' -> PhobosDemoColorpickers.
		'Special inputs' -> PhobosDemoSpecialInputs.
		'Labels' -> PhobosDemoLabels.
		'Popups' -> PhobosDemoPopups.
		'Tabs' -> PhobosDemoTabs.
		'Splitters' -> PhobosDemoSplitters.
		'Stacks and Decks' -> PhobosDemoStacksAndDecks.
		'Progressmeters' -> PhobosDemoProgressmeters.
		'Scrolling' -> PhobosDemoScrolling.
		'Menubars, etc.' -> PhobosDemoMenubars.
		'Grids' -> PhobosDemoGrids.
		'Cropping' -> PhobosDemoCropping.
		'Trees, Custom' -> PhobosDemoTreesCustom.
		'Trees, Nested' -> PhobosDemoTreesNested.
		'Trees, Simple' -> PhobosDemoTreesSimple.
		'Components' -> PhobosDemoComponents.
		'Sections' -> PhobosDemoSections.
	}